wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: huggingface
    huggingface_version: 4.15.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.9.5
    start_time: 1667794294.487478
    t:
      1:
      - 1
      - 2
      - 3
      - 9
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 2
      - 3
      - 9
      - 11
      - 41
      - 49
      - 55
      3:
      - 7
      - 23
      4: 3.9.5
      5: 0.13.5
      6: 4.15.0
      8:
      - 1
      - 3
      - 5
